# Generated by Django 5.1.4 on 2024-12-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='No address provided'),
            preserve_default=False,
        ),
    ]
